### ISSUE TITLE
Support minification of $routeProvider resolve functions

### ISSUE THREAD

**Issue by Siyfion** [btford/ngmin#35]
At the moment the only part of my code that doesn't minify properly are my resolve functions in my $routeProvider.when() statements.

It would be nice to see these supported. :+1:

**Comment by btford** [comment]
+1; I'm currently re-writing ngmin to use [Astral](https://github.com/btford/astral), but this will be the next feature I add.

**Comment by meenie** [comment]
I just realised this myself about 30 mins ago and had to change all of our resolve functions heh.

@btford, thanks a ton for your work on this, I really appreciate it :+1:

**Comment by spacenick** [comment]
That would be dope for "any" resolve actually! (I'm using ui-router and $stateProvider for my routes)
Cheers @btford this tool is insane.

**Comment by lpaulger** [comment]
+1

**Comment by mlegenhausen** [comment]
+1

**Comment by thesamet** [comment]
+1

**Comment by btford** [comment]
Added a test here: https://github.com/btford/ngmin/blob/master/test/route-provider.js#L24

If you have any other cases, please send a PR. Implementation to follow soon.

**Comment by btford** [comment]
Closed via https://github.com/btford/astral-angular-annotate/commit/e1573102233c716168815dbdbff7f1d502c8c8ec

Reinstall ngmin to get the latest relevant dependency with the fix.

**Comment by Siyfion** [comment]
@btford Is this worthy of a up-rev? That way we can just update from bower. :question:

**Comment by btford** [comment]
You don't update `ngmin` via bower.

**Comment by Siyfion** [comment]
Eak, npm even :/
—

**Comment by btford** [comment]
If you update via `npm` you should get the new updated dependencies. There's no need to bump the version.

**Comment by thesamet** [comment]
The test you referred to (https://github.com/btford/ngmin/blob/master/test/route-provider.js#L24) does not handle resolve functions.

I have added an example of (a failing) test case:

https://github.com/thesamet/ngmin/commit/6171c7bce038567ad39697d205bbfaa7c8f6c19f

**Comment by Siyfion** [comment]
@btford And I remember what I meant now, grunt-ngmin is currently pulling ngmin in for me, however it's pulling in v0.4.0 which obviously doesn't have this fix (as yet). Is it possible we could have an interim update to grunt-ngmin?

**Comment by danieljsinclair** [comment]
I could do with this

**Comment by mlegenhausen** [comment]
There is no support for the resolve object. I added it to the astral annotations.

btford/astral-angular-annotate#2

**Comment by homburg** [comment]
This issue does not seem to be fixed yet. See https://github.com/btford/ngmin/issues/35#issuecomment-20398839

**Comment by mlegenhausen** [comment]
It isn't. It only works for inline controller definition as shown in the tests.

**Comment by homburg** [comment]
Are there plans for solving this or including your pull request?

**Comment by mlegenhausen** [comment]
I haven't get any feedback yet. But you can use my fork and install it via the git url.

**Comment by homburg** [comment]
Thank you. I have added your fork to my npm dependencies and it solves the
issue perfectly.

**Comment by mboudreau** [comment]
+1.  Please fix this.  This is completely stopping us from a production build.

**Comment by btford** [comment]
> This is completely stopping us from a production build.

You do know that you can add the annotation yourself, right? There's no reason this should _ever_ hold up anything.

**Comment by mlegenhausen** [comment]
@mboudreau For now modify your `package.json` as follows:

```
devDependencies: {
  "astral-angular-annotate": "git+https://github.com/werk85/astral-angular-annotate.git"
  ...
}
```

and your problems are solved until the fix is validated and accepted by @btford.

**Comment by mboudreau** [comment]
I tried that without success. It seems that the dependency doesn't seem to
override the ngmin dependency. Am I missing something?

**Comment by mlegenhausen** [comment]
Uninstall `grunt-ngmin` or `ngmin` from your `node_modules` and install it again.

**Comment by mboudreau** [comment]
Awesome. Let me try that. Thanks bud.

**Comment by mboudreau** [comment]
Yeah, no dice, still not working even after uninstall, re-installing
astral-angular-annotate, and installing ngmin and grunt-ngmin afterwards...

On Thu, Sep 26, 2013 at 9:00 PM, Michel Boudreau
michelboudreau@gmail.comwrote:

> Awesome. Let me try that. Thanks bud.
> On Sep 26, 2013 8:45 PM, "Malte Legenhausen" notifications@github.com
> wrote:
> 
> > Uninstall grunt-ngmin or ngmin from your node_modules and install it
> > again.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/btford/ngmin/issues/35#issuecomment-25158310
> > .

## 

"If at first you don't succeed, use a bigger hammer." - Unofficial motto of
the Royal Electrical and Mechanical Engineers

**Comment by tlvince** [comment]
To confirm, when this lands, will it support [ui-router `$stateProvider` controllers](https://github.com/angular-ui/ui-router/wiki#controllers)?

**Comment by paulmelnikow** [comment]
+1

**Comment by mlegenhausen** [comment]
@tlvince I don't think so. You will need to add your own annotation rules.

I think the best way would be a plugable annotation system, cause there are many more places where you need this stuff.

**Comment by szimek** [comment]
Is it already implemented in some unreleased version of ngmin or astral-angular-annotate?

**Comment by mlegenhausen** [comment]
@szimek add the dependency manually to your dependency list. Then ngmin will pick up the new one.

**Comment by mlegenhausen** [comment]
I think the main release this doesn't get resolved is that the annotation system needs to be more adaptable. There are so many other libraries out there that would benefit from annotation support e.g. ui-router. So ngmin should not be responsible for the minification support for all the libraries but should offer an extensible system.

**Comment by szimek** [comment]
@mlegenhausen I can agree with it, but it would be also great if the current non-extensible version of ngmin supported at least pure angular out of the box. It's already fixed and only a matter of merging a PR and releasing a new version. It doesn't conflict in any way with rewriting ngmin to support some kind of plugin system in the future.

**Comment by mlegenhausen** [comment]
Cause `ngRoute` is not a core component anymore the next step needs to be an extensible system. If you want to keep ngmin for the core this should not be resolved.

Making ngmin extensible shouldn't be a big problem. Maybe I find some time to solve this.

**Comment by szimek** [comment]
Right, I forgot `ngRoute` was removed from core in 1.2.0.

**Comment by mlegenhausen** [comment]
Done. Look at my pull request #61 and vote for it ;)

**Comment by eddiemonge** [comment]
Please try https://github.com/olov/ng-annotate. ngmin is now deprecated: https://github.com/btford/ngmin/issues/93

If your issue isn't resolved there please open an issue at https://github.com/olov/ng-annotate/issues

If you really want ngmin to fix this issue, feel free to fork it and use that.
